<!DOCTYPE Mobile [
    <!ELEMENT Mobile (Company, Model, Price, Accessories)>
    <!ELEMENT Company (#PCDATA)>
    <!ELEMENT Model (#PCDATA)>
    <!ELEMENT Price (#PCDATA)>
    <!ELEMENT Accessories (#PCDATA)>
    <!ATTLIST Model Type CDATA "Camera">
    <!ENTITY HP SYSTEM "hp.txt">
    <!ENTITY CH SYSTEM "ch.txt">
    <!ENTITY SK SYSTEM "sk.txt">
]>
<Mobile>
    <Company> Nokia </Company>
    <Model Type="Camera"> 6600 </Model>
    <Price> 9999 </Price>
    <Accessories> &HP;, &CH; and a &SK; </Accessories>
</Mobile>hp.txt
Head Phones
ch.txt
Charger
sk.txt
Starters Kit