=== vuquanghuy2001/VuQuangHuy_Java/hoc_XML/Macromedia_Dreamweaver/CS4_8.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Books" type="BookType">
        <xs:complexType name="AuthorType">
            <xs:sequence>
                <xs:element name="Name" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="PublisherType">
            <xs:sequence>
                <xs:element name="Name" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="BookType">
            <xs:sequence>
                <xs:element name="Title" type="xs:string" />
                <xs:element name="Author" type="ComposerType" maxOccurs="unbounded" />
                <xs:element name="Publisher" type="PublisherType" minOccurs="0" maxOccurs="unbounded" />

=== vuquanghuy2001/VuQuangHuy_Java/hoc_XML/Macromedia_Dreamweaver/CS4_8.xml
<?xml version="1.0" ?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CS4_8.xsd">
    <Title>A cup of tea</Title>
    <Author>
        <Name>Dennis Compton</Name>
    </Author>
    <Author>
        <Name>George Ford</Name>
    </Author>
    <Publisher>
        <Name>Orange</Name>
    </Publisher>
</Books>
